repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: \.py$
      - id: ruff-format
        files: \.py$
  - repo: local
    hooks:
      - id: run-sh-scripts
        name: Run sh_scripts.sh
        entry: src/sh_scripts.sh
        language: system
        always_run: true
        pass_filenames: false