default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: uv-sync

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.7  # Use the latest stable Ruff version
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.2  # Use the latest stable isort version
    hooks:
      - id: isort
